### ISSUE TITLE
Failed to fetch pipeline nodesdetail via API

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#18]
### Request detail

```bash
curl 'http://192.168.49.2:30880/kapis/devops.kubesphere.io/v1alpha2/devops/devops-projectlgr6w/pipelines/devops-pipeline/runs/1/nodesdetail/?limit=10000' \
  -H 'Connection: keep-alive' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'Accept: */*' \
  -H 'Referer: http://192.168.49.2:30880/devops-workspace/clusters/default/devops/devops-projectlgr6w/pipelines/devops-pipeline/run/1/task-status' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Cookie: lang=en; oAuthLoginInfo=; JSESSIONID.d2f2dd82=node0y1qggafmz0y4jhpjgin6x5gr277.node0; token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTYyNDYwNDIzMSwiaWF0IjoxNjI0NTk3MDMxLCJpc3MiOiJrdWJlc3BoZXJlIiwibmJmIjoxNjI0NTk3MDMxfQ.svP1mcEtq7olHDk3KUPKMG9pzVpXdmZAp-9QIMFRo3o; expire=1624604241296; refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidG9rZW5fdHlwZSI6InJlZnJlc2hfdG9rZW4iLCJleHAiOjE2MjQ2MTE0MzEsImlhdCI6MTYyNDU5NzAzMSwiaXNzIjoia3ViZXNwaGVyZSIsIm5iZiI6MTYyNDU5NzAzMX0.gcMUDQ9zWxUx7Bk6U1gERxTaR_q6kQOTMuyyBEQ3thU' \
  --compressed \
  --insecure
```

### Response detail

```
HTTP/1.1 502 Bad Gateway
Vary: Accept-Encoding
date: Fri, 25 Jun 2021 06:19:00 GMT
content-length: 0
connection: close
```

### ks-devops-apiserver error log

```go
2021/06/25 06:19:00 http: panic serving 172.17.0.1:7987: runtime error: invalid memory address or nil pointer dereference

goroutine 2539 [running]:

net/http.(*conn).serve.func1(0xc0018da640)

/usr/local/go/src/net/http/server.go:1795 +0x139

panic(0x1be0940, 0x32f2db0)

/usr/local/go/src/runtime/panic.go:679 +0x1b2

kubesphere.io/devops/pkg/kapis/devops/v1alpha2.(*ProjectPipelineHandler).approvableCheck(0xc000870e40, 0xc00093f080, 0x1, 0x4, 0x0, 0x0, 0xc001386db0, 0x13, 0xc001386dce, 0xf, ...)

/workspace/pkg/kapis/devops/v1alpha2/devops.go:343 +0xf1

kubesphere.io/devops/pkg/kapis/devops/v1alpha2.(*ProjectPipelineHandler).GetNodesDetail(0xc000870e40, 0xc000ecc330, 0xc0001e97a0)

/workspace/pkg/kapis/devops/v1alpha2/devops.go:467 +0x406

github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc000ecc3c0, 0xc000ecc330, 0xc0001e97a0)

/go/pkg/mod/github.com/emicklei/go-restful@v2.9.6+incompatible/filter.go:21 +0x8b

kubesphere.io/devops/pkg/apiserver.logRequestAndResponse(0xc000ecc330, 0xc0001e97a0, 0xc000ecc3c0)

/workspace/pkg/apiserver/apiserver.go:322 +0x82

github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc000ecc3c0, 0xc000ecc330, 0xc0001e97a0)

/go/pkg/mod/github.com/emicklei/go-restful@v2.9.6+incompatible/filter.go:19 +0x65

github.com/emicklei/go-restful.(*Container).dispatch(0xc0009514d0, 0x2361a20, 0xc000646540, 0xc0008f9f00)

/go/pkg/mod/github.com/emicklei/go-restful@v2.9.6+incompatible/container.go:282 +0x7fb

net/http.HandlerFunc.ServeHTTP(0xc00086dc70, 0x2361a20, 0xc000646540, 0xc0008f9f00)

/usr/local/go/src/net/http/server.go:2036 +0x44

net/http.(*ServeMux).ServeHTTP(0xc000873100, 0x2361a20, 0xc000646540, 0xc0008f9f00)

/usr/local/go/src/net/http/server.go:2416 +0x1bd

github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc0009514d0, 0x2361a20, 0xc000646540, 0xc0008f9f00)

/go/pkg/mod/github.com/emicklei/go-restful@v2.9.6+incompatible/container.go:300 +0x4d

kubesphere.io/devops/pkg/apiserver/filters.WithKubeAPIServer.func1(0x2361a20, 0xc000646540, 0xc0008f9f00)

/workspace/pkg/apiserver/filters/kubeapiserver.go:62 +0x37f

net/http.HandlerFunc.ServeHTTP(0xc0003d7b80, 0x2361a20, 0xc000646540, 0xc0008f9f00)

/usr/local/go/src/net/http/server.go:2036 +0x44

kubesphere.io/devops/pkg/apiserver/filters.WithRequestInfo.func1(0x2361a20, 0xc000646540, 0xc0008f9e00)

/workspace/pkg/apiserver/filters/requestinfo.go:69 +0x3c5

net/http.HandlerFunc.ServeHTTP(0xc0009c3830, 0x2361a20, 0xc000646540, 0xc0008f9e00)

/usr/local/go/src/net/http/server.go:2036 +0x44

net/http.serverHandler.ServeHTTP(0xc000646380, 0x2361a20, 0xc000646540, 0xc0008f9e00)

/usr/local/go/src/net/http/server.go:2831 +0xa4

net/http.(*conn).serve(0xc0018da640, 0x236a020, 0xc001662f00)

/usr/local/go/src/net/http/server.go:1919 +0x875

created by net/http.(*Server).Serve

/usr/local/go/src/net/http/server.go:2957 +0x384
```

**Comment by LinuxSuRen** [comment]
This problem caused by no auth module in `ks-devops`.

**Comment by LinuxSuRen** [comment]
I guess this issue was fixed by a PR (I cannot figure out which it is).

![image](https://user-images.githubusercontent.com/1450685/134804094-3bc68612-072a-4481-9f98-15755435e3e5.png)

So, can we just close this issue? Or, if you want to verify it? @JohnNiang

**Comment by JohnNiang** [comment]
Currently, this is no problem to close this issue.

/close
