### ISSUE TITLE
Failed to start Jenkins  when using the nightly-20210923 build

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#253]
### What is the kind of this issue?

/kind bug

### Describe

Failed to start Jenkins  when using the nightly-20210923 build, and the error log detail is as following:

<details>
<summary>Error log</summary>

```java
 Picked up JAVA_TOOL_OPTIONS: -Xms512m -Xmx512m -XX:MaxRAM=2g -Dhudson.slaves.NodeProvisioner.initialDelay=20 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Dhudson.model.LoadStatistics.clock=5000 -Dhudson.model.LoadStatistics.decay=0.2 -Dhudson.slaves.NodeProvisioner.recurrencePeriod=5000 -Dio.jenkins.plugins.casc.ConfigurationAsCode.initialDelay=10000 -verbose:gc -Xloggc:/var/jenkins_home/gc-%t.log -XX:NumberOfGCLogFiles=2 -XX:+UseGCLogFileRotation -XX:GCLogFileSize=100m -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintGCCause -XX:+PrintTenuringDistribution -XX:+PrintReferenceGC -XX:+PrintAdaptiveSizePolicy -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:+DisableExplicitGC -XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions 

 Running from: /usr/share/jenkins/jenkins.war

 webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")

 2021-09-24 04:37:01.840+0000 [id=1]	INFO	org.eclipse.jetty.util.log.Log#initialized: Logging initialized @281ms to org.eclipse.jetty.util.log.JavaUtilLog

 2021-09-24 04:37:02.128+0000 [id=1]	INFO	winstone.Logger#logInternal: Beginning extraction from war file

 2021-09-24 04:37:02.216+0000 [id=1]	WARNING	o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath

 2021-09-24 04:37:02.345+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: jetty-9.4.30.v20200611; built: 2020-06-11T12:34:51.929Z; git: 271836e4c1f4612f12b7bb13ef5a92a927634b0d; jvm 1.8.0_242-b08

 2021-09-24 04:37:03.138+0000 [id=1]	INFO	o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet

 2021-09-24 04:37:03.340+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0

 2021-09-24 04:37:03.341+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults

 2021-09-24 04:37:03.346+0000 [id=1]	INFO	o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 660000ms

 2021-09-24 04:37:04.531+0000 [id=1]	INFO	hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")

 2021-09-24 04:37:04.835+0000 [id=1]	INFO	o.e.j.s.handler.ContextHandler#doStart: Started w.@2235eaab{Jenkins v2.249.1,/,file:///var/jenkins_home/war/,AVAILABLE}{/var/jenkins_home/war}

 2021-09-24 04:37:04.928+0000 [id=1]	INFO	o.e.j.server.AbstractConnector#doStart: Started ServerConnector@180bc464{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}

 2021-09-24 04:37:04.929+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: Started @3370ms

 2021-09-24 04:37:04.930+0000 [id=21]	INFO	winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled

 2021-09-24 04:37:07.328+0000 [id=26]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization

 2021-09-24 04:37:09.828+0000 [id=26]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins

 2021-09-24 04:37:12.651+0000 [id=26]	INFO	ruby.RubyRuntimePlugin#start: Injecting JRuby into XStream

 2021-09-24 04:37:50.032+0000 [id=26]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins

 2021-09-24 04:37:54.945+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins

 2021-09-24 04:37:55.414+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions

 2021-09-24 04:37:55.918+0000 [id=27]	INFO	jenkins.model.Jenkins#setBuildsAndWorkspacesDir: Using non default workspaces directories: ${JENKINS_HOME}/workspace/${ITEM_FULLNAME}.

 2021-09-24 04:37:57.635+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: System config loaded

 2021-09-24 04:37:57.943+0000 [id=27]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed ConfigurationAsCode.init

 io.jenkins.plugins.casc.ConfiguratorException: Found conflicting configuration at YamlSource: /var/jenkins_home/casc_configs/jenkins_user.yaml  in /var/jenkins_home/casc_configs/jenkins_user.yaml, line 2, column 9:

       mode: EXCLUSIVE

             ^

 	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:139)

 	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:125)

 	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:125)

 	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:52)

 Caused: io.jenkins.plugins.casc.ConfiguratorException: Failed to read YamlSource: /var/jenkins_home/casc_configs/jenkins_user.yaml

 	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:56)

 	at io.jenkins.plugins.casc.yaml.YamlUtils.loadFrom(YamlUtils.java:150)

 	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:614)

 	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:298)

 	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:290)

 Caused: java.lang.reflect.InvocationTargetException

 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

 	at java.lang.reflect.Method.invoke(Method.java:498)

 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)

 Caused: java.lang.Error

 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)

 	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)

 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)

 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)

 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)

 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)

 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)

 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

 	at java.lang.Thread.run(Thread.java:748)

 2021-09-24 04:37:57.947+0000 [id=20]	SEVERE	hudson.util.BootFailure#publish: Failed to initialize Jenkins

 io.jenkins.plugins.casc.ConfiguratorException: Found conflicting configuration at YamlSource: /var/jenkins_home/casc_configs/jenkins_user.yaml  in /var/jenkins_home/casc_configs/jenkins_user.yaml, line 2, column 9:

       mode: EXCLUSIVE

             ^

 	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:139)

 	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:125)

 	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:125)

 	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:52)

 Caused: io.jenkins.plugins.casc.ConfiguratorException: Failed to read YamlSource: /var/jenkins_home/casc_configs/jenkins_user.yaml

 	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:56)

 	at io.jenkins.plugins.casc.yaml.YamlUtils.loadFrom(YamlUtils.java:150)

 	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:614)

 	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:298)

 	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:290)

 Caused: java.lang.reflect.InvocationTargetException

 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

 	at java.lang.reflect.Method.invoke(Method.java:498)

 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)

 Caused: java.lang.Error

 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)

 	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)

 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)

 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)

 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)

 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)

 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)

 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

 	at java.lang.Thread.run(Thread.java:748)

 Caused: org.jvnet.hudson.reactor.ReactorException

 	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)

 	at jenkins.InitReactorRunner.run(InitReactorRunner.java:50)

 	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1164)

 	at jenkins.model.Jenkins.<init>(Jenkins.java:964)

 	at hudson.model.Hudson.<init>(Hudson.java:85)

 	at hudson.model.Hudson.<init>(Hudson.java:81)

 	at hudson.WebAppMain$3.run(WebAppMain.java:282)

 Caused: hudson.util.HudsonFailedToLoad

 	at hudson.WebAppMain$3.run(WebAppMain.java:299)

 2021-09-24 04:37:58.021+0000 [id=20]	INFO	jenkins.model.Jenkins#cleanUp: Stopping Jenkins

 2021-09-24 04:37:58.132+0000 [id=20]	INFO	jenkins.model.Jenkins$18#onAttained: Started termination

 2021-09-24 04:37:58.243+0000 [id=20]	INFO	jenkins.model.Jenkins$18#onAttained: Completed termination

 2021-09-24 04:37:58.244+0000 [id=20]	INFO	jenkins.model.Jenkins#_cleanUpDisconnectComputers: Starting node disconnection

 2021-09-24 04:37:58.247+0000 [id=20]	INFO	jenkins.model.Jenkins#_cleanUpShutdownPluginManager: Stopping plugin manager

 2021-09-24 04:37:58.427+0000 [id=20]	INFO	jenkins.model.Jenkins#_cleanUpPersistQueue: Persisting build queue

 2021-09-24 04:37:58.519+0000 [id=20]	INFO	jenkins.model.Jenkins#_cleanUpAwaitDisconnects: Waiting for node disconnection completion

 2021-09-24 04:37:58.522+0000 [id=20]	INFO	jenkins.model.Jenkins#cleanUp: Jenkins stopped
```

</details>

### Steps to test

```bash
# Create cluster with KubeSphere installed
kk create cluster --with-kubesphere nightly-20210923

# Enable devops
kubectl patch -nkubesphere-system cc ks-installer --type=json -p='[{"op": "replace", "path": "/spec/devops/enabled", "value": true}]'
```

**Comment by LinuxSuRen** [comment]
Please provide the steps.

**Comment by JohnNiang** [comment]
> Please provide the steps.

Thanks for your remainder. I've updated the test steps.

BTW, I found the Jenkins image might be incorrect: `kubesphere/ks-jenkins:2.249.1`. As far as I know, we need use this release of ks-jenkins: <https://github.com/kubesphere/ks-jenkins/releases/tag/v3.2.0-rc0-2.249.1>.

**Comment by LinuxSuRen** [comment]
The image tag was correct. See https://github.com/kubesphere-sigs/ks-devops-helm-chart/blob/8992d5b1f569f8f239be1db56f5c46c1fd481c6d/charts/ks-devops/charts/jenkins/values.yaml#L11

**Comment by LinuxSuRen** [comment]
The problem might caused by https://github.com/kubesphere/ks-installer/blob/b3e3982ab75d3ca131b18b45a61c40df5de82cdf/roles/ks-devops/templates/ks-devops-values.yaml.j2#L102
