### ISSUE TITLE
Controller crashed with panic when it starts

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#269]
### What happened?

Controller crashed with panic when it starts.

### Step to reproduce

Unknown. Need to inspect.

### Full stack

```go
 W0926 23:37:54.477833       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.

 I0926 23:37:54.480153       1 server.go:151] setting up manager

 I0926 23:37:54.509527       1 listener.go:44] controller-runtime/metrics "msg"="metrics server is starting to listen"  "addr"=":8080"

 I0926 23:37:54.511431       1 server.go:185] Starting cache resource from apiserver...

 I0926 23:37:54.511465       1 server.go:188] Starting the controllers.

 I0926 23:37:54.514901       1 internal.go:391] controller-runtime/manager "msg"="starting metrics server"  "path"="/metrics"

 I0926 23:37:54.515975       1 controller.go:142] controller "msg"="Starting EventSource" "controller"="pipelinerun" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="PipelineRun" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"pipelineRef":null},"status":{}}}

 I0926 23:37:54.516044       1 pipeline_controller.go:187] starting pipeline controller

 I0926 23:37:54.516199       1 devopsproject_controller.go:185] starting devops project controller

 I0926 23:37:54.516237       1 devopscredential_controller.go:192] starting devopscredential controller

 I0926 23:37:54.516431       1 controller.go:142] controller "msg"="Starting EventSource" "controller"="pipeline" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="Pipeline" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"type":""},"status":{}}}

 I0926 23:37:54.516478       1 jenkinsconfig_controller.go:125] starting Jenkins config controller

 I0926 23:37:54.516615       1 s2ibinary_controller.go:170] starting s2ibinary controller

 I0926 23:37:54.516688       1 s2irun_controller.go:172] starting s2irun controller

 I0926 23:37:54.617827       1 controller.go:149] controller "msg"="Starting Controller" "controller"="pipeline" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="Pipeline" 

 I0926 23:37:54.617887       1 controller.go:176] controller "msg"="Starting workers" "controller"="pipeline" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="Pipeline" "worker count"=1

 I0926 23:37:54.618604       1 jenkinsconfig_controller.go:302] syncing key:kubesphere-devops-system/jenkins-casc-config

 I0926 23:37:54.619551       1 controller.go:149] controller "msg"="Starting Controller" "controller"="pipelinerun" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="PipelineRun" 

 I0926 23:37:54.619597       1 controller.go:176] controller "msg"="Starting workers" "controller"="pipelinerun" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="PipelineRun" "worker count"=1

 E0926 23:37:54.641820       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)

 goroutine 317 [running]:

 k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1aa7680, 0x2be8460)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:74 +0xa6

 k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:48 +0x86

 panic(0x1aa7680, 0x2be8460)

 	/usr/local/go/src/runtime/panic.go:965 +0x1b9

 github.com/beevik/etree.(*Element).Text(0x0, 0x1d0ca31, 0xb)

 	/go/pkg/mod/github.com/beevik/etree@v1.1.0/etree.go:426 +0x26

 kubesphere.io/devops/pkg/client/devops/jenkins.getParametersfromEtree(0xc000922b40, 0xc000c628e0, 0x2, 0xc000922e40)

 	/workspace/pkg/client/devops/jenkins/pipeline_internal.go:219 +0x8f5

 kubesphere.io/devops/pkg/client/devops/jenkins.parsePipelineConfigXml(0xc000cfad80, 0xc8a, 0xc8a, 0x0, 0x0)

 	/workspace/pkg/client/devops/jenkins/pipeline_internal.go:146 +0x1f4

 kubesphere.io/devops/pkg/client/devops/jenkins.(*Jenkins).GetProjectPipelineConfig(0xc000352ed0, 0xc000ade500, 0x16, 0xc000320a04, 0x3, 0x1, 0x0, 0x0)

 	/workspace/pkg/client/devops/jenkins/project_pipeline.go:155 +0x687

 kubesphere.io/devops/controllers/pipeline.(*Controller).syncHandler(0xc0006e8d20, 0xc000ade500, 0x1a, 0xd9b78f, 0xc0009e1188)

 	/workspace/controllers/pipeline/pipeline_controller.go:265 +0x7b2

 kubesphere.io/devops/controllers/pipeline.(*Controller).processNextWorkItem.func1(0xc0006e8d20, 0x1a0a760, 0xc000c26070, 0x0, 0x0)

 	/workspace/controllers/pipeline/pipeline_controller.go:157 +0xe7

 kubesphere.io/devops/controllers/pipeline.(*Controller).processNextWorkItem(0xc0006e8d20, 0x203001)

 	/workspace/controllers/pipeline/pipeline_controller.go:164 +0x4d

 kubesphere.io/devops/controllers/pipeline.(*Controller).worker(...)

 	/workspace/controllers/pipeline/pipeline_controller.go:175

 k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000b7e000)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155 +0x5f

 k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000b7e000, 0x1ff0b40, 0xc000b54000, 0x1, 0xc0007c80c0)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156 +0x9b

 k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000b7e000, 0x3b9aca00, 0x0, 0x1, 0xc0007c80c0)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133 +0x98

 k8s.io/apimachinery/pkg/util/wait.Until(0xc000b7e000, 0x3b9aca00, 0xc0007c80c0)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90 +0x4d

 created by kubesphere.io/devops/controllers/pipeline.(*Controller).Run

 	/workspace/controllers/pipeline/pipeline_controller.go:195 +0x1f0

 panic: runtime error: invalid memory address or nil pointer dereference [recovered]

 	panic: runtime error: invalid memory address or nil pointer dereference

 [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xc86626]

 

 goroutine 317 [running]:

 k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:55 +0x109

 panic(0x1aa7680, 0x2be8460)

 	/usr/local/go/src/runtime/panic.go:965 +0x1b9

 github.com/beevik/etree.(*Element).Text(0x0, 0x1d0ca31, 0xb)

 	/go/pkg/mod/github.com/beevik/etree@v1.1.0/etree.go:426 +0x26

 kubesphere.io/devops/pkg/client/devops/jenkins.getParametersfromEtree(0xc000922b40, 0xc000c628e0, 0x2, 0xc000922e40)

 	/workspace/pkg/client/devops/jenkins/pipeline_internal.go:219 +0x8f5

 kubesphere.io/devops/pkg/client/devops/jenkins.parsePipelineConfigXml(0xc000cfad80, 0xc8a, 0xc8a, 0x0, 0x0)

 	/workspace/pkg/client/devops/jenkins/pipeline_internal.go:146 +0x1f4

 kubesphere.io/devops/pkg/client/devops/jenkins.(*Jenkins).GetProjectPipelineConfig(0xc000352ed0, 0xc000ade500, 0x16, 0xc000320a04, 0x3, 0x1, 0x0, 0x0)

 	/workspace/pkg/client/devops/jenkins/project_pipeline.go:155 +0x687

 kubesphere.io/devops/controllers/pipeline.(*Controller).syncHandler(0xc0006e8d20, 0xc000ade500, 0x1a, 0xd9b78f, 0xc0009e1188)

 	/workspace/controllers/pipeline/pipeline_controller.go:265 +0x7b2

 kubesphere.io/devops/controllers/pipeline.(*Controller).processNextWorkItem.func1(0xc0006e8d20, 0x1a0a760, 0xc000c26070, 0x0, 0x0)

 	/workspace/controllers/pipeline/pipeline_controller.go:157 +0xe7

 kubesphere.io/devops/controllers/pipeline.(*Controller).processNextWorkItem(0xc0006e8d20, 0x203001)

 	/workspace/controllers/pipeline/pipeline_controller.go:164 +0x4d

 kubesphere.io/devops/controllers/pipeline.(*Controller).worker(...)

 	/workspace/controllers/pipeline/pipeline_controller.go:175

 k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000b7e000)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155 +0x5f

 k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000b7e000, 0x1ff0b40, 0xc000b54000, 0x1, 0xc0007c80c0)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156 +0x9b

 k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000b7e000, 0x3b9aca00, 0x0, 0x1, 0xc0007c80c0)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133 +0x98

 k8s.io/apimachinery/pkg/util/wait.Until(0xc000b7e000, 0x3b9aca00, 0xc0007c80c0)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90 +0x4d

 created by kubesphere.io/devops/controllers/pipeline.(*Controller).Run

 	/workspace/controllers/pipeline/pipeline_controller.go:195 +0x1f0
```

/kind bug

**Comment by LinuxSuRen** [comment]
What is the image tag? Hash code?

**Comment by JohnNiang** [comment]
> What is the image tag? Hash code?

Because this panic only appeared in my environment which docker image of `devops-controller` was built by myself.

I'm going to close this issue and reopen this issue util I find a reproduction step.

/close
