### ISSUE TITLE
When kubesphere uses external Jenkins for synchronization, errors are reported due to different accounts

### ISSUE THREAD

**Issue by tengxunchao** [kubesphere/ks-devops#336]
We use kubesphere to connect with external Jenkins, but our kubesphre account is inconsistent with that of external Jenkins
The problem is that the account used by kubesphere to synchronize Jenkins data does not exist in the external Jenkins, resulting in an error. 
Can I use a fixed account instead of the current account when synchronizing Jenkins in kubesphere? A fixed account is similar to admin. 
Please help analyze whether this scheme is feasible?
If possible, how should kubesphre be configured?

The following are the synchronization errors due to different accounts:

```java
2021-10-29 05:57:37.058+0000 [id=86]	WARNING	i.k.j.d.a.KubesphereApiTokenAuthenticator#authenticate: API token matched for user tengxunchao but the impersonation failed
org.springframework.security.core.userdetails.UsernameNotFoundException: Password is not set: tengxunchao
	at hudson.security.HudsonPrivateSecurityRealm.load(HudsonPrivateSecurityRealm.java:197)
	at hudson.security.HudsonPrivateSecurityRealm.loadUserByUsername2(HudsonPrivateSecurityRealm.java:189)
	at jenkins.security.ImpersonatingUserDetailsService2.loadUserByUsername(ImpersonatingUserDetailsService2.java:29)
	at jenkins.security.ImpersonatingUserDetailsService2.loadUserByUsername(ImpersonatingUserDetailsService2.java:29)
	at hudson.model.User.getUserDetailsForImpersonation2(User.java:403)
	at hudson.model.User.getUserDetailsForImpersonation(User.java:426)
Caused: org.acegisecurity.userdetails.UsernameNotFoundException: org.springframework.security.core.userdetails.UsernameNotFoundException: Password is not set: tengxunchao; nested exception is org.springframework.security.core.userdetails.UsernameNotFoundException: Password is not set: tengxunchao
	at org.acegisecurity.userdetails.UsernameNotFoundException.fromSpring(UsernameNotFoundException.java:58)
	at org.acegisecurity.AuthenticationException.fromSpring(AuthenticationException.java:98)
	at hudson.model.User.getUserDetailsForImpersonation(User.java:428)
	at io.kubesphere.jenkins.devops.auth.KubesphereApiTokenAuthenticator.authenticate(KubesphereApiTokenAuthenticator.java:47)
	at jenkins.security.BasicHeaderAuthenticator.authenticate2(BasicHeaderAuthenticator.java:43)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:79)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:62)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:109)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:168)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:51)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:36)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:279)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.lang.Thread.run(Thread.java:748)
2021-10-29 05:57:37.090+0000 [id=86]	WARNING	h.i.i.InstallUncaughtExceptionHandler#handleException: Caught unhandled exception with ID 9e895e25-d86f-4ace-b9c5-2a4cf55e11d2
org.springframework.security.core.userdetails.UsernameNotFoundException: Password is not set: tengxunchao
	at hudson.security.HudsonPrivateSecurityRealm.load(HudsonPrivateSecurityRealm.java:197)
	at hudson.security.HudsonPrivateSecurityRealm.loadUserByUsername2(HudsonPrivateSecurityRealm.java:189)
	at jenkins.security.ImpersonatingUserDetailsService2.loadUserByUsername(ImpersonatingUserDetailsService2.java:29)
	at jenkins.security.ImpersonatingUserDetailsService2.loadUserByUsername(ImpersonatingUserDetailsService2.java:29)
	at hudson.model.User.getUserDetailsForImpersonation2(User.java:403)
	at hudson.model.User.getUserDetailsForImpersonation(User.java:426)
```

**Comment by gitzhuww** [comment]
kubesphere 我配置外部Jenkins，会出现401未授权错误
![image](https://user-images.githubusercontent.com/40748699/160343643-198fb3b8-57e1-4801-980c-bfdbbda95780.png)

**Comment by gitzhuww** [comment]
按照这个文章配置之后，在构建流水线的时候，还是出现这种问题，是不是casc也需要配置呢？https://github.com/kubesphere/ks-devops/issues/429
<img width="186" alt="image" src="https://user-images.githubusercontent.com/40748699/160375896-b35b37d6-31ac-402b-9b52-f361da465626.png">

**Comment by LinuxSuRen** [comment]
We didn't modify any code lines of Jenkins. So any connection errors with Jenkins is out of the scope.

/kind support
/close
