### ISSUE TITLE
error syncing the credential

### ISSUE THREAD

**Issue by chengleqi** [kubesphere/ks-devops#809]
### What is version of KubeSphere DevOps has the issue?

ks-devops master branch

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

Kubernetes v1.24.4+k3s1 on Rancher Desktop 1.5.1

### What happened?

I want to add a git credential. But the console print out the `error syncing` message.

### Relevant log output

```shell
E0901 15:05:01.881358   15289 devopscredential_controller.go:168] error syncing 'my-devops-projectsxwph/gitee': unexpected status code: 500, requeuing
E0901 15:05:01.971687   15289 devopscredential_controller.go:167] error syncing 'my-devops-projectsxwph/gitee': unexpected status code: 500, requeuingcould not reconcile devopsProject
E0901 15:05:01.971707   15289 devopscredential_controller.go:168] error syncing 'my-devops-projectsxwph/gitee': unexpected status code: 500, requeuing
E0901 15:05:02.065107   15289 devopscredential_controller.go:167] error syncing 'my-devops-projectsxwph/gitee': unexpected status code: 500, requeuingcould not reconcile devopsProject
E0901 15:05:02.065127   15289 devopscredential_controller.go:168] error syncing 'my-devops-projectsxwph/gitee': unexpected status code: 500, requeuing
E0901 15:05:02.161542   15289 devopscredential_controller.go:167] error syncing 'my-devops-projectsxwph/gitee': unexpected status code: 500, requeuingcould not reconcile devopsProject
```

### Additional information

```markdown
Here is the log in devops-jenkins

2022-09-01 07:16:23.810+0000 [id=11]	WARNING	h.i.i.InstallUncaughtExceptionHandler#handleException: Caught unhandled exception with ID 075b291b-5eec-409f-8913-4653d3e5b1e3
org.kohsuke.stapler.NoStaplerConstructorException: There's no @DataBoundConstructor on any constructor of interface com.cloudbees.plugins.credentials.Credentials
	at org.kohsuke.stapler.ClassDescriptor.loadConstructorParamNames(ClassDescriptor.java:289)
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:786)
	at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:85)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:690)
Caused: java.lang.IllegalArgumentException: Failed to instantiate interface com.cloudbees.plugins.credentials.Credentials from {"credentials":{"metadata":{"name":"gitee","namespace":"my-devops-projectsxwph","uid":"8a045ac4-cd07-4839-be56-d1feb7054513","resourceVersion":"3259","creationTimestamp":"2022-09-01T07:05:00Z","labels":{"app":"gitee"},"annotations":{"credential.devops.kubesphere.io/autosync":"true","credential.devops.kubesphere.io/datahash":"765775f7f7","credential.devops.kubesphere.io/syncstatus":"successful","credential.devops.kubesphere.io/synctime":"2022-09-01 07:05:00.676878791 +0000 UTC m=+596.098108702","kubesphere.io/creator":"chengleqi"},"finalizers":["finalizers.kubesphere.io/credential"],"managedFields":[{"manager":"apiserver","operation":"Update","apiVersion":"v1","time":"2022-09-01T07:05:00Z","fieldsType":"FieldsV1","fieldsV1":{"f:data":{".":{},"f:password":{},"f:username":{}},"f:metadata":{"f:annotations":{".":{},"f:credential.devops.kubesphere.io/autosync":{},"f:credential.devops.kubesphere.io/synctime":{},"f:kubesphere.io/creator":{}},"f:labels":{".":{},"f:app":{}}},"f:type":{}}},{"manager":"main","operation":"Update","apiVersion":"v1","time":"2022-09-01T07:05:00Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:credential.devops.kubesphere.io/syncstatus":{}},"f:finalizers":{".":{},"v:\"finalizers.kubesphere.io/credential\"":{}}}}}]},"data":{"password":"","username":"Y2hlbmdsZXFp"},"type":"credential.devops.kubesphere.io/basic-auth"}}
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:693)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:490)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:486)
	at com.cloudbees.plugins.credentials.CredentialsStoreAction$CredentialsWrapper.doUpdateSubmit(CredentialsStoreAction.java:1407)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:393)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:405)
	at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:77)
	at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:208)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:141)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:536)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
Caused: javax.servlet.ServletException
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:816)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:281)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:281)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:281)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:457)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:281)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:694)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:240)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:156)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:248)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:153)
	at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:80)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:153)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:153)
	at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:60)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:153)
	at com.cloudbees.jenkins.support.slowrequest.SlowRequestFilter.doFilter(SlowRequestFilter.java:37)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:153)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:153)
	at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:153)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:159)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:153)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:92)
	at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:53)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:121)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:92)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at jenkins.security.BasicHeaderProcessor.success(BasicHeaderProcessor.java:139)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:86)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:62)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:109)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:51)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:85)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:39)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by LinuxSuRen** [comment]
hi @chengleqi , thanks for reporting this issue. Happy to be able to fix this before we have a release.

**Comment by LinuxSuRen** [comment]
This issue caused by https://github.com/kubesphere/ks-devops/blob/796dbc70dffe9f94e37a6e8080aaeedc1c13f852/pkg/client/devops/jclient/credential.go#L40

See also https://github.com/kubesphere/ks-devops/blob/796dbc70dffe9f94e37a6e8080aaeedc1c13f852/pkg/client/devops/jclient/credential.go#L31

We should convert the type to a correct one before passing to the Jenkins client.

/good-first-issue

**Comment by chengleqi** [comment]
I'd like to tackle this one.
/assign

**Comment by chengleqi** [comment]
I kinda stuck here.
I change the following function
https://github.com/kubesphere/ks-devops/blob/796dbc70dffe9f94e37a6e8080aaeedc1c13f852/pkg/client/devops/jclient/credential.go#L38
to this
```golang
func (j *JenkinsClient) UpdateCredentialInProject(projectID string, credential *v1.Secret) (id string, err error) {
	client := j.getClient()

	var cre interface{}
	if cre, err = util.ConvertSecretToCredential(credential); err != nil {
		return "", err
	}
	err = client.UpdateInFolder(projectID, credential.GetName(), cre)
	return
}
```

And the request that send to jenkins is:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/53958238/187934767-3d9aa4dc-29b3-4f7a-a1e8-568876188e16.png">
and the payload json is:
```json
{
    "credentials":{
        "description":"",
        "DisplayName":"",
        "Fingerprint":null,
        "FullName":"",
        "id":"gitee",
        "TypeName":"",
        "$class":"com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl",
        "stapler-class":"com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl",
        "scope":"GLOBAL",
        "username":"chengleqi",
        "password":"xxx"
    }
}
```
And I got the same error.
And I also try "PUT" and "PATCH" method in the UpdateInFolder func in the jenkins-zh/jenkins-client module. It didn't work.

**Comment by LinuxSuRen** [comment]
Below is the old code link. Perhaps it could help you have a better understanding.

https://github.com/kubesphere/ks-devops/blob/fa720aeecf9fbe02b95dcf59cb22c55daf55f23e/pkg/client/devops/jenkins/credential.go#L250

**Comment by gaffeyQiu** [comment]
> I kinda stuck here. I change the following function
> 
> https://github.com/kubesphere/ks-devops/blob/796dbc70dffe9f94e37a6e8080aaeedc1c13f852/pkg/client/devops/jclient/credential.go#L38
> 
> 
> to this
> ```go
> func (j *JenkinsClient) UpdateCredentialInProject(projectID string, credential *v1.Secret) (id string, err error) {
> 	client := j.getClient()
> 
> 	var cre interface{}
> 	if cre, err = util.ConvertSecretToCredential(credential); err != nil {
> 		return "", err
> 	}
> 	err = client.UpdateInFolder(projectID, credential.GetName(), cre)
> 	return
> }
> ```
> 
> The request that send to jenkins is: <img alt="image" width="752" src="https://user-images.githubusercontent.com/53958238/187934767-3d9aa4dc-29b3-4f7a-a1e8-568876188e16.png"> and the payload json is:
> 
> ```json
> {
>     "credentials":{
>         "description":"",
>         "DisplayName":"",
>         "Fingerprint":null,
>         "FullName":"",
>         "id":"gitee",
>         "TypeName":"",
>         "$class":"com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl",
>         "stapler-class":"com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl",
>         "scope":"GLOBAL",
>         "username":"chengleqi",
>         "password":"xxx"
>     }
> }
> ```
> 
> Then I got the same error. I also try "PUT" and "PATCH" method in the UpdateInFolder func in the jenkins-zh/jenkins-client module. It didn't work.

I think the parameters of create credential api and update credential api are not the same.  
The update credential api don't need `credentials ` key.

![image](https://user-images.githubusercontent.com/19790443/188052105-592818f8-39f4-44ed-a619-fa80fa1aaf69.png)
![image](https://user-images.githubusercontent.com/19790443/188052142-d0b5b849-5055-4630-a395-c43b2e5fa668.png)
![image](https://user-images.githubusercontent.com/19790443/188052183-13094be3-485a-4cd0-9841-7ce3fb7dba68.png)
![image](https://user-images.githubusercontent.com/19790443/188052202-d4c19721-0fa8-4f0a-999b-1b28ec4610b8.png)
